DROP TABLE IF EXISTS content;
DROP TABLE IF EXISTS word;
DROP TABLE IF EXISTS tag;

CREATE TABLE tag(
tagId SERIAL PRIMARY KEY,
tagName VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE word(
wordId SERIAL PRIMARY KEY,
word VARCHAR(255) NOT NULL UNIQUE,
pronounce VARCHAR(255) NOT NULL,
haveTag TEXT,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
--FOREIGN KEY(haveTagId) REFERENCES haveTag(id)
);

create table content(
contentId SERIAL PRIMARY KEY,
wordId INTEGER,
haveTag TEXT,
content TEXT,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY(wordId) REFERENCES word(wordId)
--FOREIGN KEY(haveTagId) REFERENCES haveTag(id)
);
